### ISSUE TITLE
err:invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by recoilme** [go-telegram-bot-api/telegram-bot-api#118] opened 2017-09-01 11:58 UTC
Sometimes i see this error in logs. Is it 400/500 error from telegram server?

**Comment by zhuharev** [comment] 2017-10-29 21:09
can you provide more details?

**Comment by automatthias** [comment] 2017-11-28 17:34
I'm seeing this too. It's reproducible. When I leave my bot active e.g. overnight and it always dies with this message:

```
2017/11/23 01:58:07 api.go:38: response map[data:<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.0</center>
</body>
</html>
]
2017/11/23 01:58:07 lang-bot.go:109: invalid character '<' looking for beginning of value
```

The exit code is 1.

**Comment by zhuharev** [comment] 2017-11-28 22:26
@recoilme  it's looks like telegram's backend server is down.

You can handle this error and not panicing/os.exit from app.

Also we need to detect and handle not a json response.

**Comment by automatthias** [comment] 2017-12-02 10:06
Hello,

I've just realized that I've submitted this update to a wrong project. The API that I'm using is github.com/bot-api/telegram. I started searching by the error message, landed here, and didn't notice that this is a different implementation of the API. Sorry about that!

Maciej

**Comment by recoilme** [comment] 2017-12-06 16:28
Hi @zhuharev 
I think we must check http response status code before processing to json
Telegram may response with 429 error code for example: https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this
Or with 50x code - if servers down at this moment

may i write on russian?
Очень много не нравится в апи(
Некоторых вещей не хватает, например поля caption_entities - https://core.telegram.org/bots/api#message

Часть приходится делать в 2 запроса, потому что в интерфейсе доступно только обращение по чатид, хотя метод подразумевает доступ и по юзернэйм(

Нет обработки лимитов на запросы.
Нет обработки http статусов ответов
Нет обработки таймаутов сетевых соединений

Очень жалею что не начал писать свое(
С другой стороны лучшего апи сейчас для гоу нет( Такие дела..

**Comment by Syfaro** [comment] 2017-12-06 18:31
Error codes are returned as part of the [JSON response](https://core.telegram.org/bots/api#making-requests), so it should still be valid JSON even when getting an error. However, it does appear to be returning HTML periodically. It's likely additional validations need to be added to ignore these garbage responses.

**Comment by zhuharev** [comment] 2017-12-07 12:19
@recoilme tnx for your contribution. I also wanted to write my own library, but this is open source, we can make the library even better together.

I change your post to todo-list and I will close it slowly.

I like @Syfaro develop a library in my spare time and the repository needs maintainers (#122)

**Comment by mappu** [comment] 2018-06-17 00:02
In June 2018 these errors still occur from time-to-time. But they only affect logging, not a serious problem.

Caused by use of `getUpdatesChan` from https://github.com/go-telegram-bot-api/telegram-bot-api/blob/master/bot.go#L489 .

```
2018/06/11 13:13:33 invalid character '<' looking for beginning of value
2018/06/11 13:13:33 Failed to get updates, retrying in 3 seconds...
2018/06/12 13:13:24 invalid character '<' looking for beginning of value
2018/06/12 13:13:24 Failed to get updates, retrying in 3 seconds...
2018/06/12 13:13:28 invalid character '<' looking for beginning of value
2018/06/12 13:13:28 Failed to get updates, retrying in 3 seconds...
2018/06/13 13:13:38 invalid character '<' looking for beginning of value
2018/06/13 13:13:38 Failed to get updates, retrying in 3 seconds...
2018/06/15 13:22:25 invalid character '<' looking for beginning of value
2018/06/15 13:22:25 Failed to get updates, retrying in 3 seconds...
```

**Closed** 2018-10-08 06:52 UTC
Labels: Enhancement, question
